server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: dongkwon
    password:
    platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: mySuperSecretKey
  token-validity-in-seconds: 86400
